/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docsSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  docsSidebar: [
    "intro",
    {
      "type": "category",
      "label": "getting-started",
      "link": {
        "type": "generated-index"
      },
      "collapsed": false,
      "items": [
        "getting-started/prepare",
        {
          "type": "category",
          "label": "getting-started-install",
          "link": {
            "type": "generated-index"
          },
          "items": [
            "getting-started/install/docker-compose",
            "getting-started/install/docker",
            "getting-started/install/1panel",
            "getting-started/install/fast-jar",
            "getting-started/install/flutter-app"
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "user-guide",
      "link": {
        "type": "generated-index"
      },
      "items": [
        "user-guide/common",
        "user-guide/attachments",
        "user-guide/subjects",
        "user-guide/plugins",
        "user-guide/settings",
        "user-guide/users",
        "user-guide/collections",
        "user-guide/faq"
      ]
    },
    {
      "type": "category",
      "label": "plugins",
      "link": {
        "type": "generated-index"
      },
      "items": [
        "plugins/common",
        "plugins/plugin-bgmtv",
        "plugins/plugin-local-files-import",
        "plugins/plugin-jellyfin",
        "plugins/plugin-mikan",
        "plugins/plugin-baidupan",
        "plugins/plugin-alist"
      ]
    },
    "about"
  ],
  
};

module.exports = sidebars;
